CREATE TABLE USERS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UNIQUE (NAME)
);
CREATE TABLE ROLES (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UNIQUE (NAME)
);